# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.5.0-buster@sha256:c0e2b08d46685b9e3f2bd0b1293f726587760e93db29338dcf5eb2008ca6d3bf
    working_directory: ~/docker-smtp
    steps:
      - checkout
      - run: 
          name: LintGit
          command: |
            sudo echo ${CIRCLE_BRANCH}
            sudo npm i -g commitlint @commitlint/config-conventional
            sudo echo "module.exports = { extends:[\"@commitlint/config-conventional\"] }" > commitlint.config.js
            sudo echo ${CIRCLE_BRANCH} | grep -Eqv "^(feature/|bugfix/|hotfix/|release/)" && echo "Wrong branch name, please use feature/, bugfix/, hotfix/ or release/ as prefix ${CIRCLE_BRANCH}" && exit 1
            commitlint --config ./commitlint.config.js --to $(git rev-parse origin/${CIRCLE_BRANCH}) --from $(git rev-parse origin/develop)

workflows:
  CI-docker-smtp:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
              - master
